### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by lowks**
Simplify `.travis.yml` by using native elixir

### CODE REVIEW

**Comment by fishcakez** [comment]
Awesome thanks, I'll merge when tests pass.

**Comment by fishcakez** [comment]
Oh they didn't.

**Comment by lowks** [comment]
Looks like the tests failing with version 1.0.3. Let me fix it up so that it does not run against that first.

**Comment by lowks** [comment]
Looks like it passed now, but then with 1.0.3 and latest version `dbg` does not work.

**Comment by fishcakez** [comment]
Can you remove the second commit and try again I think I fixed the issue.

**Comment by lowks** [comment]
All passed now ! :+1:

**Comment by fishcakez** [comment]
Thank you!

**Pull request merged**
