### PR TITLE
Add markdown as a dependency for docs

### PR DESCRIPTION
**Pull request by johnhamelink**
Hey there, I've added a few small tweaks to this package:

 - I added `/cover` and `/doc` to the gitignore
   - `/doc` is generated when `mix docs` is ran
   - `/cover` was the only line missing from [gitignore.io](https://www.gitignore.io/api/elixir)
 - I added the markdown dependency for the docs environment, so that the docs can be compiled.

Thanks

JH

### CODE REVIEW

**Comment by fishcakez** [comment]
Thank you updating this, could we use `earmark` from hex instead of `markdown` from github? I would prefer not to introduce a NIF when possible, fetching from hex should be faster and I would rather point at a more precise tag or reference than just `master`.

Since we are improving this could please bump the `ex_doc` version to something more recent to get the new style and change `only` to `:dev` (it is hassle to set `MIX_ENV=docs`). That means dropping support for elixir 0.15 which is fine.

**Comment by johnhamelink** [comment]
@fishcakez done that :+1:

**Comment by fishcakez** [comment]
Thanks

**Comment by johnhamelink** [comment]
@fishcakez sorry, forgot to add the second half of your recommendations - I will submit a separate PR for that so I don't rewrite history.

**Comment by fishcakez** [comment]
NP, can you also make sure that the ex_doc requirement matches the lock file, "0.11.1" is not "~> 0.7".

**Pull request merged**
